apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-ms-backend-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-ms-backend-tier
  template:
    metadata:
      labels:
        app: notification-ms-backend-tier
    spec:
      containers:
        - name: notification-ms-backend
          image: srthealikk/flight-notification-ms:1.0.2
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: jdbc:postgresql://postgresql-svc-cip:5432/postgres
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: '123456'
            - name: USER_MS_HOST
              value: "34.76.44.68"
            - name: APP_PORT
              value: "80"
            - name: KAFKA_HOST
              value: "kafka:9092"
            - name: FRONT_SERVER
              value: "104.155.109.215"
