spring:
  application:
    name: notification-ms
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}

  profiles:
    include:
     - email
     - db

  security:
    jwt-secret-key: eW91ci0yNTYtYml0LXNlY3JldHlvdXItMjU2LWJpdC1zZWNyZXR5b3VyLTI1Ni1iaXQtc2VjcmV0eW91ci0yNTYtYml0LXNlY3JldHlvdXItMjU2LWJpdC1zZWNyZXR5b3VyLTI1Ni1iaXQtc2VjcmV0
server:
  port: 8090


application:
  user-ms:
    server: ${USER_MS_HOST:localhost}
  front:
    server: ${FRONT_SERVER:localhost:63342/flight-reservation-front}


