apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-ms-backend-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-ms-backend-tier
  template:
    metadata:
      labels:
        app: flight-ms-backend-tier
        svc: flight-ms-backend-svc
    spec:
      containers:
        - name: flight-ms-backend
          image: srthealikk/flight-ms:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: jdbc:postgresql://postgresql-svc-cip:5432/postgres
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: '123456'
            - name: APP_HOST
              value: "34.76.44.68"
            - name: APP_PORT
              value: "80"
            - name: KAFKA_HOST
              value: "kafka:9092"
