name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Detect-Changes:
    runs-on: ubuntu-latest
    outputs:
      changed_services: ${{ steps.detect.outputs.services }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Detect Changed Microservices
        id: detect
        run: |
          # Checking the status of the repository to detect any changes
          echo "Checking for changes in the microservices..."

          # Check for uncommitted changes
          CHANGED_FILES=$(git status --porcelain)

          if [ -z "$CHANGED_FILES" ]; then
            echo "No uncommitted changes detected."
          else
            echo "Detected the following changes:"
            echo "$CHANGED_FILES"
          fi

          # Find changed services from the specific folders
          CHANGED_SERVICES=$(echo "$CHANGED_FILES" | grep -E '^(M|A|D)\s+(flight-ms|user-ms|notification-ms)' | cut -d' ' -f2 | cut -d'/' -f1 | sort -u | tr '\n' ',')

          if [ -z "$CHANGED_SERVICES" ]; then
            echo "No changes detected in the specified microservices."
          else
            echo "Detected changes in the following services: $CHANGED_SERVICES"
            echo "services=${CHANGED_SERVICES}" >> $GITHUB_ENV
          fi
        env:
          services: ${{ env.services }}



  Build-and-Deploy:
    needs: Detect-Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images for Changed Microservices
        run: |
          # Eğer değişen servisler varsa, Docker image'ları oluştur ve push et
          if [ -z "${{ needs.Detect-Changes.outputs.changed_services }}" ]; then
            echo "No services detected for build and deploy."
          else
            for service in $(echo ${{ needs.Detect-Changes.outputs.changed_services }} | tr ',' ' '); do
              echo "Building and pushing Docker image for $service..."
              docker build -t ${{ secrets.DOCKER_USERNAME }}/$service:latest $service
              docker push ${{ secrets.DOCKER_USERNAME }}/$service:latest
            done
          fi

      - name: Deploy to Kubernetes
        run: |
          # Eğer değişen servisler varsa, Kubernetes üzerine deploy et
          if [ -z "${{ needs.Detect-Changes.outputs.changed_services }}" ]; then
            echo "No services detected for Kubernetes deployment."
          else
            for service in $(echo ${{ needs.Detect-Changes.outputs.changed_services }} | tr "," " "); do
              echo "Deploying $service to Kubernetes..."
              kubectl apply -f k8s/$service-deploy.yaml
            done
          fi
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
          ZONE_NAME: ${{ secrets.GKE_ZONE_NAME }}
