name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Gradle-Docker-Build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: gradle


      - name: Ensure gradlew has execute permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Generate Docker tag
        id: generate_tag
        run: echo "tag=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV


      - name: Build Docker image
        run: |
          cd user-ms
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-ms:${{ env.tag }} -f Dockerfile .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/user-ms:${{ env.tag }}




  Deploy:
    needs: Gradle-Docker-Build
    runs-on: ubuntu-latest
    steps:

          

      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Update Kubernetes Deployment file
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/user-ms:${{ env.tag }}|" k8s/user-ms-deploy.yaml

      - name: kubectl - Google Cloud GKE cluster
        uses: ameydev/gke-kubectl-action@master
        with:
          args: |
            apply -f k8s/user-ms-deploy.yaml
            kubectl rollout restart deployment/user-ms-backend-app-deployment
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
          ZONE_NAME: ${{ secrets.GKE_ZONE_NAME }}










